//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsumptionOrders
    {
        public int CO_ID { get; set; }
        public Nullable<int> MC_ID { get; set; }
        public Nullable<int> S_ID { get; set; }
        public Nullable<decimal> CO_TotalPrice { get; set; }
        public Nullable<System.DateTime> CO_CreateTime { get; set; }
        public Nullable<byte> CO_Status { get; set; }
    
        public virtual MemCards MemCards { get; set; }
        public virtual Shops Shops { get; set; }
    }
}
