//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemberWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferLogs
    {
        public int TL_ID { get; set; }
        public int S_ID { get; set; }
        public int U_ID { get; set; }
        public Nullable<int> TL_FromMC_ID { get; set; }
        public string TL_FromMC_CardID { get; set; }
        public Nullable<int> TL_ToMC_ID { get; set; }
        public string TL_ToMC_CardID { get; set; }
        public decimal TL_TransferMoney { get; set; }
        public string TL_Remark { get; set; }
        public System.DateTime TL_CreateTime { get; set; }
    
        public virtual Shops Shops { get; set; }
        public virtual Users Users { get; set; }
    }
}
